import Link from "next/link";
import type { ReactNode } from "react";

export const legalPages = [
  { key: "terms", title: "Terms and Conditions", href: "/legal/terms" },
  { key: "privacy", title: "Privacy Policy", href: "/legal/privacy" },
  {
    key: "acceptable-use",
    title: "Acceptable Use Policy",
    href: "/legal/acceptable-use",
  },
  {
    key: "responsible-disclosure",
    title: "Responsible Disclosure Policy",
    href: "/legal/responsible-disclosure",
  },
  { key: "refund", title: "Refund Policy", href: "/legal/refund" },
  {
    key: "data-processing",
    title: "Data Processing Notice",
    href: "/legal/data-processing",
  },
  { key: "cookie", title: "Cookie Policy", href: "/legal/cookie" },
  {
    key: "security-policy",
    title: "Security Policy",
    href: "/legal/security-policy",
  },
  { key: "disclaimer", title: "Disclaimer", href: "/legal/disclaimer" },
];

export const legalDocs: Record<string, { title: string; sections: string[] }> =
  {
    terms: {
      title: "Terms and Conditions",
      sections: [
        "SecureMSME AI may be used only for websites, applications, domains and systems that you own or are explicitly authorized to assess.",
        "The platform is designed for safe public checks, reporting, developer remediation workflows, retest proof and monitoring. It must not be used for unauthorized access, exploitation, brute force, disruption or data extraction.",
        "SecureMSME AI does not guarantee 100% security, does not guarantee all vulnerabilities are found and does not provide legal compliance certification.",
        "Paid plans can be activated manually after admin approval of payment reference. Do not submit card data, OTPs, UPI PINs or bank passwords.",
      ],
    },
    privacy: {
      title: "Privacy Policy",
      sections: [
        "We may process account data, website URLs, scan metadata, security findings, reports, support messages, payment reference information and usage logs.",
        "Data is used to provide security review workflows, generate reports, track fixes, retest proof, monitoring, billing approval and support.",
        "Do not upload passwords, OTPs, card numbers, private keys, session cookies, confidential customer records or production secrets unless a future enterprise agreement explicitly supports that workflow.",
        "Reports may be shared through client portal links generated by the user. Users are responsible for sharing links with authorized recipients only.",
      ],
    },
    "acceptable-use": {
      title: "Acceptable Use Policy",
      sections: [
        "You may use SecureMSME AI for authorized website security review, developer remediation, client reporting, retest proof and monitoring.",
        "You must not use the platform for unauthorized scanning, brute force, exploitation, malware, credential theft, bypassing access controls, harassment, disruption or illegal activity.",
        "Before scanning any target, you must confirm ownership or written permission.",
        "Violations can lead to suspension, cancellation, report removal and cooperation with valid legal requests.",
      ],
    },
    "responsible-disclosure": {
      title: "Responsible Disclosure Policy",
      sections: [
        "If you find a security issue in SecureMSME AI, report it through the support/security disclosure channel.",
        "Act in good faith, avoid privacy violations, avoid service disruption and do not access, modify or delete data that is not yours.",
        "Please give us reasonable time to investigate and fix before public disclosure.",
        "This policy does not promise a bug bounty reward unless a separate written program says so.",
      ],
    },
    refund: {
      title: "Refund Policy",
      sections: [
        "Paid plans are activated after manual admin approval. If a submitted payment cannot be verified, the request may be rejected.",
        "Refund requests should be sent to support with payment reference, plan and reason. Eligibility depends on plan status, usage and applicable law.",
        "Completed security reports, consumed scan credits and custom/manual work may be non-refundable unless required otherwise by law.",
        "SecureMSME AI manual billing does not collect or store card data, UPI PINs, OTPs or bank passwords.",
      ],
    },
    "data-processing": {
      title: "Data Processing Notice",
      sections: [
        "Security reports, scan results, developer tasks, monitoring alerts and client portal data are processed to provide the platform services.",
        "Users control which websites they add, which reports they generate and which portal links they share.",
        "Do not add targets or data unless you are authorized to process that security information.",
        "Support can assist with reasonable deletion/export requests subject to security and legal constraints.",
      ],
    },
    cookie: {
      title: "Cookie Policy",
      sections: [
        "SecureMSME AI may use cookies or similar technologies for login sessions, security, preferences and basic analytics.",
        "Authentication and security cookies may be required for the service to work.",
        "If analytics are enabled, they should be configured to minimize unnecessary personal data collection.",
        "You can control cookies through browser settings, but disabling required cookies may break login or dashboard features.",
      ],
    },
    "security-policy": {
      title: "Security Policy",
      sections: [
        "SecureMSME AI uses authentication, database row-level security, admin checks and safe-by-design workflows.",
        "The platform provides AI-assisted review, evidence-backed reports, developer fix workflows, retest proof and monitoring. It does not guarantee complete security.",
        "Users must not submit passwords, OTPs, private keys, card data, session cookies or other secrets into manual payment or support fields.",
        "Security issues should be reported through support or responsible disclosure channels.",
      ],
    },
    disclaimer: {
      title: "Disclaimer",
      sections: [
        "SecureMSME AI does not guarantee that a website, application, company or system is 100% secure.",
        "The platform does not guarantee that every vulnerability, risk or misconfiguration will be found.",
        "Reports, dashboards, benchmarks and launch readiness scores are not legal compliance certificates.",
        "Users must use SecureMSME AI only with ownership or written authorization.",
      ],
    },
  };

export function LegalIndex() {
  return (
    <section className="space-y-8">
      <div className="rounded-3xl border border-blue-200 bg-blue-50 p-8">
        <p className="text-sm font-black text-blue-700">Legal Center</p>
        <h1 className="mt-2 text-4xl font-black text-blue-950">
          SecureMSME AI Legal Pages
        </h1>
        <p className="mt-4 max-w-4xl leading-8 text-blue-900">
          Launch templates for safe, authorized and transparent use. Get legal
          review before full public paid launch.
        </p>
      </div>
      <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">
        {legalPages.map((page) => (
          <Link
            key={page.key}
            href={page.href}
            className="rounded-3xl border border-slate-200 bg-white p-6 hover:bg-slate-50"
          >
            <h2 className="text-xl font-black">{page.title}</h2>
            <p className="mt-3 text-sm leading-6 text-slate-600">
              Read current 2026-01 launch template.
            </p>
          </Link>
        ))}
      </div>
    </section>
  );
}

export function LegalDocumentPage({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <article className="mx-auto max-w-4xl space-y-8">
      <div className="rounded-3xl border border-slate-200 bg-white p-8">
        <p className="text-sm font-black text-slate-500">
          Version 2026-01 · Template
        </p>
        <h1 className="mt-2 text-4xl font-black">{title}</h1>
        <p className="mt-4 leading-7 text-slate-600">
          This is an operational template, not legal advice. Get legal review
          before full public paid launch.
        </p>
      </div>
      <div className="space-y-4 rounded-3xl border border-slate-200 bg-white p-8 text-slate-700">
        {children}
      </div>
      <div className="rounded-3xl border border-red-200 bg-red-50 p-6 text-sm font-bold leading-7 text-red-900">
        SecureMSME AI does not guarantee 100% security, does not claim all
        vulnerabilities are found, does not provide legal compliance
        certification, and must be used only with authorization.
      </div>
    </article>
  );
}
